### ISSUE TITLE
Import bug in 3.3.3_3

### ISSUE THREAD

**Issue by richardgsands** [fourseven/meteor-scss#135]
Breaks ionic-sass and ionicons-sass:

```
   While processing files with fourseven:scss (for target web.browser):
   /client/css/app.scss: Scss compiler error: File to import:
   .meteor/local/build/programs/server/assets/packages/meteoric_ionic-sass/ionic not found. Import origin:
   /client/css/app.scss
```

Fixed by downgrading to 3.2.0: ```meteor add fourseven:scss@=3.2.0```

**Comment by sebakerckhof** [comment]
try version 3.4.0-beta1

**Comment by boxxa** [comment]
Yep! This fixed it for me.

    meteor add fourseven:scss@3.4.0-beta1

**Comment by sebakerckhof** [comment]
Okay, version 3.4 final will be released after some bugs in node-sass are fixed.

**Comment by hashwin** [comment]
Still an issue in v3.4.0-beta1
```
$ meteor
[[[[[ ~/code/apps/samoza ]]]]]

=> Started proxy.
=> Started MongoDB.

Changes to your project's package version selections:

fourseven:scss  upgraded from 3.2.0 to 3.4.0-beta1

=> Errors prevented startup:

   While processing files with fourseven:scss (for target web.browser):
   /client/stylesheets/samoza.scss: Scss compiler error: File to import:
   {}/client/stylesheets/.meteor/local/build/programs/server/assets/packages/meteoric_ionic-sass/_ionic
   not found in file:
   /Users/ashwin/code/apps/samoza/{}/client/stylesheets/samoza.scss


   While processing files with fourseven:scss (for target web.cordova):
   /client/stylesheets/samoza.scss: Scss compiler error: File to import:
   {}/client/stylesheets/.meteor/local/build/programs/server/assets/packages/meteoric_ionic-sass/_ionic
   not found in file:
   /Users/ashwin/code/apps/samoza/{}/client/stylesheets/samoza.scss
```

**Comment by boxxa** [comment]
3.2 fixes this. The beta does not. Should be opened still.

**Comment by sebakerckhof** [comment]
Nope, this is meteoric that should be rewritten.

**Comment by sebakerckhof** [comment]
I've created an updated package: https://atmospherejs.com/seba/ionic-sass
Note that ionicons is included, but you can choose whether to import it or not.
Ionic has also been updated to 1.1.0

**Comment by alanpachuau** [comment]
Upgraded fourseven:scss to 3.4.1 and I am having this issue

`While processing files with fourseven:scss (for target web.browser):
   /client/stylesheets/app.scss: Scss compiler error: File to import:
   {}/client/stylesheets/.meteor/local/build/programs/server/assets/packages/meteoric_ionic-sass/_ionic not found in file:
   /Users/xxxxxx/myapp/{}/client/stylesheets/app.scss`

**Fixed:**
Downgraded fourseven:scss to 3.2.0 and this issue is fixed
`meteor add fourseven:scss@=3.2.0`

**Comment by idavit** [comment]
Hey guys

I am using Meteor 1.4

@alanpachuau it is not possible to install `meteor add fourseven:scss@=3.2.0` anymore :( due to postinstall error realted to node-sass

any suggestions? how to fix issue?

   While processing files with fourseven:scss (for target web.browser):
   /client/scss/main.scss: Scss compiler error: File to import: {}/client/scss/~flexboxgrid not found in file: /Users/USER/PROJECT/editor/{}/client/scss/main.scss

I just tryed to do 
@import "~flexboxgrid";
which is installed via npm (as of bower package is depricated already :()

**Comment by wal-nadeem** [comment]
having exactly the same issue as that of @davityavryan 

Neither can downgrade to `meteor add fourseven:scss@=3.2.0` with meteor `1.4.1.3`

**Comment by datanotion** [comment]
@wal-nadeem - any luck finding a work around?  I'm fighting the same issue.

**Comment by wal-nadeem** [comment]
Sorry @datanotion I had to downgrade way down to meteor `1.2`

**Comment by datanotion** [comment]
Thanks @wal-nadeem for your quick reply.  We just migrated to .less and everything works great - compile times in Meteor 1.4 are totally worth it.
