### ISSUE TITLE
JS variables in SCSS

### ISSUE THREAD

**Issue by SachaG** [fourseven/meteor-scss#136]
I have a bit of a weird feature request, and I wonder if the new Build Plugins API might somehow make it possible. 

In Telescope, end users can define a set of custom colors to customize their app's look and feel, and those are then either stored in `settings.json` or in the DB. 

Would there be a way to get the values of these variables when building the app, and inject them right in the SCSS code? i.e. something like:

```css
body {
  background: ${Meteor.settings.public.backgroundColor};
}
```

**Comment by fourseven** [comment]
Sounds like something https://github.com/sass/node-sass#functions--v300---experimental could do, although after going through the whole compass experience (tied to ruby because the extensions were written in ruby) I'm slightly hesitant.

**Comment by sebakerckhof** [comment]
The new build api won't really help us with this and I'd personally think it is not generic enough to include. 

Would the experience be that much worse for the user if he would just edit a `_colors.scss` file instead of the settings.json file? Maybe you could have a default or empty `_colors.scss` file which you overwrite with values read from settings.json?

Alternatively, like Mathew proposes, the experimental functions support could probably be used, but it'd need some caching mechanism not to slow down the build too much.

**Comment by SachaG** [comment]
Yeah, it's probably not worth the trouble right now. I have a system that works in Telescope anyway where I generate the appropriate CSS code on the client.

**Comment by YannDanthu** [comment]
Hi,

let say I'm using a service like S3 or imgix to store all my images, then it would be a great feature to set my background-image url to be able to set them with Meteor.settings ;)

What do you think ?

**Comment by sebakerckhof** [comment]
What would be the advantage over setting it in a `_variables.scss` file?
Also, Meteor settings are intended for runtime settings, not compile-time settings.

**Comment by YannDanthu** [comment]
Third party providers' settings are platform dependent (dev, test, prod), and I don't to come with settings defined in several files (and don't want to add an extra script to populate the settings neither).
I guess IronRouter REST GET route will do the job for image urls.
