### ISSUE TITLE
Error when trying to import file

### ISSUE THREAD

**Issue by Nevtep** [fourseven/meteor-scss#163]
when I add an import linelike this (@import "{}/client/_import.scss") to any file I get this error:

 While processing files with fourseven:scss (for target web.browser):
   /client/modules/layout/layout_app.scss: Scss compiler error: media query
   expression must begin with '('

what am I doing wrong?

**Comment by sebakerckhof** [comment]
That's an error outside of this plugins code. There's likely something wrong with your scss code

**Comment by Denly** [comment]
It happens on me too. If I remove the line @import "{my-package:pretty-buttons}client/layout/styles.scss",  it can works perfectly well, but If I put the line back, it shows "Scss compiler error: media query expression must begin with '(' " again. Thus tt is probably something wrong of plugins, because both scss runs well independently. and I didn't use any "@media".
@sebakerckhof @Nevtep

**Comment by Denly** [comment]
Well, I just solved it.. it need a ";" at the end. 
ex.@import "{my-package:pretty-buttons}/buttons/_styles.scss"; 
In official README.md, it doesn't has ";". Maybe it need to be fix, (thought it's just a minor problem). 
@Nevtep

**Comment by sebakerckhof** [comment]
The sass spec indeed requires the semicolon. I updated the readme.
