### ISSUE TITLE
node-sass@3. 8.0 failed to exec install script with fourseven:scss@3.9.0

### ISSUE THREAD

**Issue by yellowiscool** [fourseven/meteor-scss#216]
Hi, I just updated to fourseven:scss@3.9.0 (no chance for me using 3.8) and I have an installation problem with it. I don't really know if it's something you can do about it, because it's node-sass that fails, but I wanted to mention the problem before I go back to Meteor 1.3.

Thanks for your work anyway :smiley: 

```
root@fd9572caa31f:/app# meteor update
=> Errors while initializing project:

While loading package fourseven:scss@3.9.0:
error: Command failed:
/root/.meteor/packages/meteor-tool/.1.4.1.186av8r++os.linux.x86_64+web.browser+w
eb.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm
rebuild --no-bin-links --update-binary
npm info it worked if it ends with ok
npm info using npm@3.10.6
npm info using node@v4.5.0
npm info readInstalled object
npm info build
/root/.meteor/packages/fourseven_scss/.3.9.0.1xe2nhg++os+web.browser+web.cordova
/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_module
s/.temp-15eh2ar/node_modules/node-sass
npm info lifecycle node-sass@3.8.0~preinstall: node-sass@3.8.0
npm info lifecycle node-sass@3.8.0~install: node-sass@3.8.0
module.js:329
throw err;
^

Error: Cannot find module
'/root/.meteor/packages/fourseven_scss/.3.9.0.1xe2nhg++os+web.browser+web.cordov
a/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modul
es/.temp-15eh2ar/node_modules/node-sass/scripts/install.js'
at Function.Module._resolveFilename (module.js:327:15)
at Function.Module._load (module.js:278:25)
at Function.Module.runMain (module.js:431:10)
at startup (node.js:141:18)
at node.js:977:3

npm info lifecycle node-sass@3.8.0~install: Failed to exec install script
npm ERR! Linux 4.4.17-boot2docker
npm ERR! argv
"/root/.meteor/packages/meteor-tool/.1.4.1.186av8r++os.linux.x86_64+web.browser+
web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"
"/root/.meteor/packages/meteor-tool/.1.4.1.186av8r++os.linux.x86_64+web.browser+
web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm"
"rebuild" "--no-bin-links" "--update-binary"
npm ERR! node v4.5.0
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE
npm ERR! node-sass@3.8.0 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.8.0 install script 'node
scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!
/root/.meteor/packages/fourseven_scss/.3.9.0.1xe2nhg++os+web.browser+web.cordova
/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_module
s/.temp-15eh2ar/npm-debug.log
npm info it worked if it ends with ok
npm info using npm@3.10.6
npm info using node@v4.5.0
npm info readInstalled object
npm info build
/root/.meteor/packages/fourseven_scss/.3.9.0.1xe2nhg++os+web.browser+web.cordova
/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_module
s/.temp-15eh2ar/node_modules/node-sass
npm info lifecycle node-sass@3.8.0~preinstall: node-sass@3.8.0
npm info lifecycle node-sass@3.8.0~install: node-sass@3.8.0
module.js:329
throw err;
^

Error: Cannot find module
'/root/.meteor/packages/fourseven_scss/.3.9.0.1xe2nhg++os+web.browser+web.cordov
a/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modul
es/.temp-15eh2ar/node_modules/node-sass/scripts/install.js'
at Function.Module._resolveFilename (module.js:327:15)
at Function.Module._load (module.js:278:25)
at Function.Module.runMain (module.js:431:10)
at startup (node.js:141:18)
at node.js:977:3

npm info lifecycle node-sass@3.8.0~install: Failed to exec install script
npm ERR! Linux 4.4.17-boot2docker
npm ERR! argv
"/root/.meteor/packages/meteor-tool/.1.4.1.186av8r++os.linux.x86_64+web.browser+
web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"
"/root/.meteor/packages/meteor-tool/.1.4.1.186av8r++os.linux.x86_64+web.browser+
web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm"
"rebuild" "--no-bin-links" "--update-binary"
npm ERR! node v4.5.0
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE
npm ERR! node-sass@3.8.0 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.8.0 install script 'node
scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!
/root/.meteor/packages/fourseven_scss/.3.9.0.1xe2nhg++os+web.browser+web.cordova
/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_module
s/.temp-15eh2ar/npm-debug.log
```

**Comment by NitroBAY** [comment]
I have 3.8.0_1 and meteor 1.4.1 but when I try to update scss to 3.9.0 
I have this : 
`=> Errors while upgrading packages:

While loading package fourseven:scss@3.9.0:
error: Command failed:
/home/NitroBAY/.meteor/packages/meteor-tool/.1.4.1.186av8r++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm
rebuild --no-bin-links --update-binary
{ [Error: EACCES: permission denied, mkdir
'/home/NitroBAY/.meteor/packages/fourseven_scss/.3.9.0.14g4uw8++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/.temp-iuo2kt/node_modules/node-sass/vendor/linux-x64-46']
errno: -13,
code: 'EACCES',
syscall: 'mkdir',
path:
'/home/NitroBAY/.meteor/packages/fourseven_scss/.3.9.0.14g4uw8++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/.temp-iuo2kt/node_modules/node-sass/vendor/linux-x64-46'
}
gyp info it worked if it ends with ok
gyp verb cli [
'/home/NitroBAY/.meteor/packages/meteor-tool/.1.4.1.186av8r++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node',
gyp verb cli
'/home/NitroBAY/.meteor/packages/fourseven_scss/.3.9.0.14g4uw8++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/node-gyp/bin/node-gyp.js',

gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.4.0
gyp info using node@4.5.0 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import platform;
print(platform.python_version());"` returned: "2.7.6\n"
gyp verb get node dir no --target version specified, falling back to host node version: 4.5.0
gyp verb command install [ '4.5.0' ]
gyp verb install input version string "4.5.0"
gyp verb install installing version: 4.5.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 4.5.0
gyp verb build dir attempting to create "build" dir:
/home/NitroBAY/.meteor/packages/fourseven_scss/.3.9.0.14g4uw8++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/.temp-iuo2kt/node_modules/node-sass/build
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir
'/home/NitroBAY/.meteor/packages/fourseven_scss/.3.9.0.14g4uw8++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/.temp-iuo2kt/node_modules/node-sass/build'
gyp ERR! stack     at Error (native)
gyp ERR! System Linux 3.4.0+
gyp ERR! command
"/home/NitroBAY/.meteor/packages/meteor-tool/.1.4.1.186av8r++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"
"/home/NitroBAY/.meteor/packages/fourseven_scss/.3.9.0.14g4uw8++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags="
"--libsass_library="
gyp ERR! cwd
/home/NitroBAY/.meteor/packages/fourseven_scss/.3.9.0.14g4uw8++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/.temp-iuo2kt/node_modules/node-sass
gyp ERR! node -v v4.5.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
Build failed

npm ERR! Linux 3.4.0+
npm ERR! argv
"/home/NitroBAY/.meteor/packages/meteor-tool/.1.4.1.186av8r++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"
"/home/NitroBAY/.meteor/packages/meteor-tool/.1.4.1.186av8r++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm"
"rebuild" "--no-bin-links" "--update-binary"
npm ERR! node v4.5.0
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE
npm ERR! node-sass@3.8.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.8.0 postinstall script 'node scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!
/home/NitroBAY/.meteor/packages/fourseven_scss/.3.9.0.14g4uw8++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/.temp-iuo2kt/npm-debug.log { [Error: EACCES: permission denied, mkdir
'/home/NitroBAY/.meteor/packages/fourseven_scss/.3.9.0.14g4uw8++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/.temp-iuo2kt/node_modules/node-sass/vendor/linux-x64-46']
errno: -13,
code: 'EACCES',
syscall: 'mkdir',
path:
'/home/NitroBAY/.meteor/packages/fourseven_scss/.3.9.0.14g4uw8++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/.temp-iuo2kt/node_modules/node-sass/vendor/linux-x64-46'
}
gyp info it worked if it ends with ok
gyp verb cli [
'/home/NitroBAY/.meteor/packages/meteor-tool/.1.4.1.186av8r++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node',
gyp verb cli
'/home/NitroBAY/.meteor/packages/fourseven_scss/.3.9.0.14g4uw8++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/node-gyp/bin/node-gyp.js',

gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.4.0
gyp info using node@4.5.0 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import platform;
print(platform.python_version());"` returned: "2.7.6\n"
gyp verb get node dir no --target version specified, falling back to host node version: 4.5.0
gyp verb command install [ '4.5.0' ]
gyp verb install input version string "4.5.0"
gyp verb install installing version: 4.5.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 4.5.0
gyp verb build dir attempting to create "build" dir:
/home/NitroBAY/.meteor/packages/fourseven_scss/.3.9.0.14g4uw8++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/.temp-iuo2kt/node_modules/node-sass/build
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir
'/home/NitroBAY/.meteor/packages/fourseven_scss/.3.9.0.14g4uw8++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/.temp-iuo2kt/node_modules/node-sass/build'
gyp ERR! stack     at Error (native)
gyp ERR! System Linux 3.4.0+
gyp ERR! command
"/home/NitroBAY/.meteor/packages/meteor-tool/.1.4.1.186av8r++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"
"/home/NitroBAY/.meteor/packages/fourseven_scss/.3.9.0.14g4uw8++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags="
"--libsass_library="
gyp ERR! cwd
/home/NitroBAY/.meteor/packages/fourseven_scss/.3.9.0.14g4uw8++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/.temp-iuo2kt/node_modules/node-sass
gyp ERR! node -v v4.5.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
Build failed

npm ERR! Linux 3.4.0+
npm ERR! argv
"/home/NitroBAY/.meteor/packages/meteor-tool/.1.4.1.186av8r++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node"
"/home/NitroBAY/.meteor/packages/meteor-tool/.1.4.1.186av8r++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm"
"rebuild" "--no-bin-links" "--update-binary"
npm ERR! node v4.5.0
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE
npm ERR! node-sass@3.8.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.8.0 postinstall script 'node scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!
/home/NitroBAY/.meteor/packages/fourseven_scss/.3.9.0.14g4uw8++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/.temp-iuo2kt/npm-debug.log


While building package materialize:materialize:
error: No plugin known to handle file 'sass/components/date_picker/_default.date.scss'. If you
want this file to be a static asset, use addAssets instead of addFiles; eg,
api.addAssets('sass/components/date_picker/_default.date.scss', 'client').
error: No plugin known to handle file 'sass/components/date_picker/_default.scss'. If you want
this file to be a static asset, use addAssets instead of addFiles; eg,
api.addAssets('sass/components/date_picker/_default.scss', 'client').
error: No plugin known to handle file 'sass/components/date_picker/_default.time.scss'. If you
want this file to be a static asset, use addAssets instead of addFiles; eg,
api.addAssets('sass/components/date_picker/_default.time.scss', 'client').
error: No plugin known to handle file 'sass/components/forms/_checkboxes.scss'. If you want this
file to be a static asset, use addAssets instead of addFiles; eg,
api.addAssets('sass/components/forms/_checkboxes.scss', 'client').
error: No plugin known to handle file 'sass/components/forms/_file-input.scss'. If you want this
file to be a static asset, use addAssets instead of addFiles; eg,
api.addAssets('sass/components/forms/_file-input.scss', 'client').
error: No plugin known to handle file 'sass/components/forms/_forms.scss'. If you want this file
to be a static asset, use addAssets instead of addFiles; eg,
api.addAssets('sass/components/forms/_forms.scss', 'client').
error: No plugin known to handle file 'sass/components/forms/_input-fields.scss'. If you want
this file to be a static asset, use addAssets instead of addFiles; eg,
api.addAssets('sass/components/forms/_input-fields.scss', 'client').
error: No plugin known to handle file 'sass/components/forms/_radio-buttons.scss'. If you want
this file to be a static asset, use addAssets instead of addFiles; eg,
api.addAssets('sass/components/forms/_radio-buttons.scss', 'client').
error: No plugin known to handle file 'sass/components/forms/_range.scss'. If you want this file
to be a static asset, use addAssets instead of addFiles; eg,
api.addAssets('sass/components/forms/_range.scss', 'client').
error: No plugin known to handle file 'sass/components/forms/_select.scss'. If you want this file
to be a static asset, use addAssets instead of addFiles; eg,
api.addAssets('sass/components/forms/_select.scss', 'client').
error: No plugin known to handle file 'sass/components/forms/_switches.scss'. If you want this
file to be a static asset, use addAssets instead of addFiles; eg,
api.addAssets('sass/components/forms/_switches.scss', 'client').
error: No plugin known to handle file 'sass/components/_buttons.scss'. If you want this file to
be a static asset, use addAssets instead of addFiles; eg,
api.addAssets('sass/components/_buttons.scss', 'client').
error: No plugin known to handle file 'sass/components/_cards.scss'. If you want this file to be
a static asset, use addAssets instead of addFiles; eg,
api.addAssets('sass/components/_cards.scss', 'client').
error: No plugin known to handle file 'sass/components/_carousel.scss'. If you want this file to
be a static asset, use addAssets instead of addFiles; eg,
api.addAssets('sass/components/_carousel.scss', 'client').
error: No plugin known to handle file 'sass/components/_chips.scss'. If you want this file to be
a static asset, use addAssets instead of addFiles; eg,
api.addAssets('sass/components/_chips.scss', 'client').
error: No plugin known to handle file 'sass/components/_collapsible.scss'. If you want this file
to be a static asset, use addAssets instead of addFiles; eg,
api.addAssets('sass/components/_collapsible.scss', 'client').
error: No plugin known to handle file 'sass/components/_color.scss'. If you want this file to be
a static asset, use addAssets instead of addFiles; eg,
api.addAssets('sass/components/_color.scss', 'client').
error: No plugin known to handle file 'sass/components/_dropdown.scss'. If you want this file to
be a static asset, use addAssets instead of addFiles; eg,
api.addAssets('sass/components/_dropdown.scss', 'client').
error: No plugin known to handle file 'sass/components/_global.scss'. If you want this file to be
a static asset, use addAssets instead of addFiles; eg,
api.addAssets('sass/components/_global.scss', 'client').
error: No plugin known to handle file 'sass/components/_grid.scss'. If you want this file to be a
static asset, use addAssets instead of addFiles; eg, api.addAssets('sass/components/_grid.scss',
'client').
error: No plugin known to handle file 'sass/components/_icons-material-design.scss'. If you want
this file to be a static asset, use addAssets instead of addFiles; eg,
api.addAssets('sass/components/_icons-material-design.scss', 'client').
error: No plugin known to handle file 'sass/components/_materialbox.scss'. If you want this file
to be a static asset, use addAssets instead of addFiles; eg,
api.addAssets('sass/components/_materialbox.scss', 'client').
error: No plugin known to handle file 'sass/components/_mixins.scss'. If you want this file to be
a static asset, use addAssets instead of addFiles; eg,
api.addAssets('sass/components/_mixins.scss', 'client').
error: No plugin known to handle file 'sass/components/_modal.scss'. If you want this file to be
a static asset, use addAssets instead of addFiles; eg,
api.addAssets('sass/components/_modal.scss', 'client').
error: No plugin known to handle file 'sass/components/_navbar.scss'. If you want this file to be
a static asset, use addAssets instead of addFiles; eg,
api.addAssets('sass/components/_navbar.scss', 'client').
error: No plugin known to handle file 'sass/components/_normalize.scss'. If you want this file to
be a static asset, use addAssets instead of addFiles; eg,
api.addAssets('sass/components/_normalize.scss', 'client').
error: No plugin known to handle file 'sass/components/_prefixer.scss'. If you want this file to
be a static asset, use addAssets instead of addFiles; eg,
api.addAssets('sass/components/_prefixer.scss', 'client').
error: No plugin known to handle file 'sass/components/_preloader.scss'. If you want this file to
be a static asset, use addAssets instead of addFiles; eg,
api.addAssets('sass/components/_preloader.scss', 'client').
error: No plugin known to handle file 'sass/components/_roboto.scss'. If you want this file to be
a static asset, use addAssets instead of addFiles; eg,
api.addAssets('sass/components/_roboto.scss', 'client').
error: No plugin known to handle file 'sass/components/_sideNav.scss'. If you want this file to
be a static asset, use addAssets instead of addFiles; eg,
api.addAssets('sass/components/_sideNav.scss', 'client').
error: No plugin known to handle file 'sass/components/_slider.scss'. If you want this file to be
a static asset, use addAssets instead of addFiles; eg,
api.addAssets('sass/components/_slider.scss', 'client').
error: No plugin known to handle file 'sass/components/_table_of_contents.scss'. If you want this
file to be a static asset, use addAssets instead of addFiles; eg,
api.addAssets('sass/components/_table_of_contents.scss', 'client').
error: No plugin known to handle file 'sass/components/_tabs.scss'. If you want this file to be a
static asset, use addAssets instead of addFiles; eg, api.addAssets('sass/components/_tabs.scss',
'client').
error: No plugin known to handle file 'sass/components/_toast.scss'. If you want this file to be
a static asset, use addAssets instead of addFiles; eg,
api.addAssets('sass/components/_toast.scss', 'client').
error: No plugin known to handle file 'sass/components/_tooltip.scss'. If you want this file to
be a static asset, use addAssets instead of addFiles; eg,
api.addAssets('sass/components/_tooltip.scss', 'client').
error: No plugin known to handle file 'sass/components/_typography.scss'. If you want this file
to be a static asset, use addAssets instead of addFiles; eg,
api.addAssets('sass/components/_typography.scss', 'client').
error: No plugin known to handle file 'sass/components/_variables.scss'. If you want this file to
be a static asset, use addAssets instead of addFiles; eg,
api.addAssets('sass/components/_variables.scss', 'client').
error: No plugin known to handle file 'sass/components/_waves.scss'. If you want this file to be
a static asset, use addAssets instead of addFiles; eg,
api.addAssets('sass/components/_waves.scss', 'client').

While loading plugin `compileScssBatch` from package `fourseven:scss`:

/home/NitroBAY/.meteor/packages/fourseven_scss/.3.9.0.14g4uw8++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/node-sass/lib/index.js:15:11:
Missing binding
/home/NitroBAY/.meteor/packages/fourseven_scss/.3.9.0.14g4uw8++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/node-sass/vendor/linux-x64-46/binding.node
Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 4.x

Found bindings for the following environments:
- Windows 32-bit with Node.js 4.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to build the binding for your current environment.
at Object.<anonymous>
(/home/NitroBAY/.meteor/packages/fourseven_scss/.3.9.0.14g4uw8++os+web.browser+web.cordova/plugin.compileScssBatch.os/npm/node_modules/meteor/compileScssBatch/node_modules/node-sass/lib/index.js:15:11)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Module.Mp.load
(/home/NitroBAY/.meteor/packages/meteor-tool/.1.4.1.186av8r++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/reify/node/runtime.js:16:23)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object.<anonymous> (/tools/isobuild/bundler.js:1569:22)
at Object.require (/tools/isobuild/bundler.js:1546:11)
at meteorInstall.node_modules.meteor.compileScssBatch.plugin.compile-scss.js
(packages/compileScssBatch/plugin/compile-scss.js:3:18)
at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:82:1)
at <runJavaScript-43>:339:1
at <runJavaScript-43>:345:3`

I install all new required toolchain and did meteor npm rebuild. `Meteor `is working fine. I was under windows 10 and switched to Windows subsystem for linux. If I come back to windows to meteor update : 
Error: Cannot find module 'meteor-promise'

**Comment by adeshpandey** [comment]
+1

**Comment by NikiN2** [comment]
+1

**Comment by sebakerckhof** [comment]
AFAIK, this should not be an issue anymore with newer meteor/fourseven:scss releases. Can re-open if the problem still occurs with meteor 1.4.3+ and fourseven:scss 4.5+
